# Generated by Django 6.0.1 on 2026-01-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
