# Generated by Django 6.0.1 on 2026-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0002_delete_appliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField()),
                ('Brand', models.CharField()),
                ('Purchase_Date', models.DateField()),
            ],
        ),
    ]
