# Generated by Django 6.0.1 on 2026-01-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
